### ISSUE TITLE
Translation bug(?)

### ISSUE THREAD

**Issue by Gnarlywhale** [squallstar/gakusei#11]
Not exactly certain what went wrong here: 
![image](https://cloud.githubusercontent.com/assets/3422267/11663983/517c8090-9d9c-11e5-8a0b-ade80c632d99.png)

On mouse over of incorrect text:
![image](https://cloud.githubusercontent.com/assets/3422267/11664012/732181aa-9d9c-11e5-87d6-eb52c1746d6e.png)

**Comment by squallstar** [comment]
Yeah I am aware that the algorithm has some issues when calculating the differences, I'm going to have a look early tomorrow and see if I can fix it.

Btw logic is here: https://github.com/squallstar/gakusei/blob/master/server/answer.js#L18

Probably related to https://github.com/squallstar/gakusei/issues/9

**Comment by squallstar** [comment]
Fixed
