### ISSUE TITLE
Option to "Skip this Question" disappears after being clicked

### ISSUE THREAD

**Issue by Gnarlywhale** [squallstar/gakusei#15]
Not sure if this is by a bug or by design.
Pre Click:
![image](https://cloud.githubusercontent.com/assets/3422267/11754762/aa1a5540-a00a-11e5-99a0-6e38e8f74af6.png)

Post Click:
![image](https://cloud.githubusercontent.com/assets/3422267/11754774/c20d1cbe-a00a-11e5-8413-eb66857bd844.png)

**Comment by squallstar** [comment]
Thanks for the fix, though it's meant to disappear so you don't keep skipping all the sentences. I was thinking to only let the user skip once, until he gets a correct question (and then the skip button becomes visible again
