### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Gnarlywhale** [squallstar/gakusei#16]
![image](https://cloud.githubusercontent.com/assets/3422267/11755058/e6be9df6-a00c-11e5-8c3e-76e6fcb81db9.png)

"さん” mistakenly translates to "Mr." despite the context of the sentence indicating the gender is female, should be "Ms."

**Comment by squallstar** [comment]
Yeah that happens because words are queried randomly in the sentence and it can happen that "sex" generates "woman" but "suffix" generates Mr instead of Mrs/miss. I'll have a look and see if I can relate those two fields so the sentence makes more sense.
