### ISSUE TITLE
I want to make it for my region, What I need to do...?

### ISSUE THREAD

**Issue by lovebdsobuj** [squallstar/gakusei#26]

**Comment by squallstar** [comment]
What? Can you please explain?

**Comment by lovebdsobuj** [comment]
I talking about **Gakusei - Test your Japanese** Android app. 

I want to make it for my region that means I want to make an Android app like 
Test your Japanese > Test your Bangla (`Bangladeshis Language`).

**Comment by squallstar** [comment]
The app is highly based on English to Japanese, and making it work with other languages might require more than one adjustment.

By the way, it should roughly work if you translate all the english sentences and words found here on these three json files:
https://github.com/squallstar/gakusei/tree/master/private/fixtures
